#
# Autogenerated by Thrift Compiler (0.9.2)
#
# DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
#

require 'thrift'
require 'hello_types'

module Hello
  class Client
    include ::Thrift::Client

    def hi()
      send_hi()
      return recv_hi()
    end

    def send_hi()
      send_message('hi', Hi_args)
    end

    def recv_hi()
      result = receive_message(Hi_result)
      return result.success unless result.success.nil?
      raise ::Thrift::ApplicationException.new(::Thrift::ApplicationException::MISSING_RESULT, 'hi failed: unknown result')
    end

  end

  class Processor
    include ::Thrift::Processor

    def process_hi(seqid, iprot, oprot)
      args = read_args(iprot, Hi_args)
      result = Hi_result.new()
      result.success = @handler.hi()
      write_result(result, oprot, 'hi', seqid)
    end

  end

  # HELPER FUNCTIONS AND STRUCTURES

  class Hi_args
    include ::Thrift::Struct, ::Thrift::Struct_Union

    FIELDS = {

    }

    def struct_fields; FIELDS; end

    def validate
    end

    ::Thrift::Struct.generate_accessors self
  end

  class Hi_result
    include ::Thrift::Struct, ::Thrift::Struct_Union
    SUCCESS = 0

    FIELDS = {
      SUCCESS => {:type => ::Thrift::Types::STRING, :name => 'success'}
    }

    def struct_fields; FIELDS; end

    def validate
    end

    ::Thrift::Struct.generate_accessors self
  end

end

